# Exercise 1a - Where are you? {-}

You are navigating in a small area, where it is sufficiently accurate to neglect the curvature of the Earth. The local convention is to specify locations in coordinates (x,y), where x is distance North from an agreed-upon landmark, and y is the distance East.
 
1. You are on a bearing of 0 degrees (North) from grid location (550m, 100m) and on a bearing of 90 degrees (East) from grid location (900m, -350m). Where are you?

In [1]:
from numpy import array, sqrt, sin, cos, tan, pi, abs
from numpy.linalg import norm
from lib.navlib import rad2deg, deg2rad, arctan, arctan2

p1 = array([[550],
            [100]])

p2 = array([[900],
            [-350]])

# Intersection
px = array([p2[0],
            p1[1]])

print(px)

[[900]
 [100]]


2. You are 100m from a point located at grid location (550m, 100m) and 200m from a point located at grid location (700m, 150m). Where are you?

In [2]:
# Point p1
p1 = array([[550],
            [100]])

# Point p2
p2 = array([[700],
            [150]])

# Radius of p1
r1 = 100

# Radius of p2
r2 = 200

# Distance between p1 and p2
d = norm(p2 - p1)
l = (r1**2 - r2**2 + d**2)/(2*d)
h = sqrt(r1**2 - l**2)

# Intersection point 1
px1 = array([p1[0] + l*(p2[0] - p1[0])/d + h*(p2[1] - p1[1])/d,
             p1[1] + l*(p2[1] - p1[1])/d - h*(p2[0] - p1[0])/d])

# Intersection point 2
px2 = array([p1[0] + l*(p2[0] - p1[0])/d - h*(p2[1] - p1[1])/d,
             p1[1] + l*(p2[1] - p1[1])/d + h*(p2[0] - p1[0])/d])

print(px1)
print(px2)

[[566.22498999]
 [  1.32503002]]
[[503.77501001]
 [188.67496998]]


3. You are 150m from a point located at grid location (550m, 100m), and on a bearing of 142 degrees (Southeast) from a point located at (1000m, -200m). Where are you?

In [3]:
# Point p1
p1 = array([[1000],
            [-200]])

# Point p2
p2 = array([[550],
            [100]])

# Radius of p1
az = deg2rad(142)

# Radius of p2
r = 150

# Azimuth/Distance between p1 and p2
az0 = arctan2(p2[1] - p1[1], p2[0] - p1[0])
alpha = az - az0
d = norm(p2 - p1)

l1 = (d - sqrt(d**2 - (1 + tan(alpha)**2)*(d**2 - r**2)))/(1 + tan(alpha)**2)
h1 = l1*tan(-alpha)

l2 = (d + sqrt(d**2 - (1 + tan(alpha)**2)*(d**2 - r**2)))/(1 + tan(alpha)**2)
h2 = l2*tan(alpha)

# Intersection point 1
px1 = array([p1[0] + l1*(p2[0] - p1[0])/d + h1*(p2[1] - p1[1])/d,
             p1[1] + l1*(p2[1] - p1[1])/d - h1*(p2[0] - p1[0])/d])

# Intersection point 2
px2 = array([p1[0] + l2*(p2[0] - p1[0])/d - h2*(p2[1] - p1[1])/d,
             p1[1] + l2*(p2[1] - p1[1])/d + h2*(p2[0] - p1[0])/d])

print(px1)
print(px2)

[[688.80287998]
 [ 43.13383688]]
[[461.24354911]
 [220.92267127]]


4. A signal from grid location (550m, 100m) arrives 500ns (1ns = 1 billionth of a second) faster than a signal from location (100m, 250m), and at (550m, 100m) 400ns faster than a signal from location (-250m, -250m). Take the speed of light to be 0.3m/ns. Where are you?

In [5]:
# Point p1
p1 = array([[550],
            [100]])

# Point p2
p2 = array([[100],
            [250]])

# Point p3
p3 = array([[-250],
            [-250]])

# Observations (m)
Delta1 = 500*0.3
Delta2 = 400*0.3

# Station distances
d1 = norm(p2 - p1)
d2 = norm(p3 - p1)

# Hyperbola 1
a1 = Delta1/2
b1 = sqrt((d1/2)**2 - a1**2)

# Hyperbola 2
a2 = Delta2/2
b2 = sqrt((d2/2)**2 - a2**2)

# Intersection
a = 1/a1**2 - b1**2/(b2**2 * a1**2)
b = 2*d1/a2**2
c = d1**2/a2**2 + b1**2/b2**2 - 1

l = (-b + sqrt(b**2 - 4*a*c))/(2*a)
h = sqrt(b1**2 * l**2/a1**2 - b1**2)

# Intersection point 1
px1 = array([p1[0] + l*(p2[0] - p1[0])/d1 + h*(p2[1] - p1[1])/d1,
             p1[1] + l*(p2[1] - p1[1])/d1 - h*(p2[0] - p1[0])/d1])

# Intersection point 2
px2 = array([p1[0] + l*(p2[0] - p1[0])/d2 - h*(p2[1] - p1[1])/d2,
             p1[1] + l*(p2[1] - p1[1])/d2 + h*(p2[0] - p1[0])/d2])

print(px1)
print(px2)

[[1052.92259542]
 [ 753.78652495]]
[[ 555.46808457]
 [-348.03394435]]
