In [1]:
from numpy import array, sqrt, eye, set_printoptions
from numpy.linalg import inv

set_printoptions(formatter={'float_kind':"{:.2f}".format})

# System values
dt = 10             # Interval [second]
q = 0.5             # Process noise [meter^2/second]

# Dynamic matrix
F = array([[0]])

# White noise coefficients
G = array([[sqrt(q)]])

# Transistion matrix
phi = eye(1)
print("\nTransition matrix:\n", phi)

# Process noise
Q = array([[q*dt]])
print("\nProcess noise matrix:\n", Q)

# Measurement
z = array([[1]])     # Measurement [meter]

# Measurement covariance matrix
R = array([[1**2]])

# Design matrix
H = array([[1]])

# Initial values
x = array([[0]])
P = array([[1]])

# Time update (prediction)
xp = phi@x
Pp = phi@P@phi.T + Q

print("\nPredicted state vector:\n", xp)
print("\nPredicted covariance matrix\n", Pp)

# Gain matrix
K = Pp@H.T@inv(H@Pp@H.T + R)

# Measurement update (correction)
x = xp + K@(z - H@xp)
P = (eye(1) - K@H)@Pp

print("\nEstimated state vector:\n", x)
print("\nEstimated covariance matrix\n", P)


Transition matrix:
 [[1.00]]

Process noise matrix:
 [[5.00]]

Predicted state vector:
 [[0.00]]

Predicted covariance matrix
 [[6.00]]

Estimated state vector:
 [[0.86]]

Estimated covariance matrix
 [[0.86]]


In [2]:
# System values
dt = 10             # Interval [second]
q = 0.25            # Process noise [meter^2/second]

# Dynamic matrix
F = array([[0, 1],
           [0, 0]])

# White noise coefficients
G = array([[0],
           [sqrt(q)]])

# Transistion matrix
phi = eye(2) + F*dt
print("\nTransition matrix:\n", phi)

# Process noise
Q = array([[1/3*q*dt**3, 1/2*q*dt**2],
           [1/2*q*dt**2, q*dt]])
print("\nProcess noise matrix:\n", Q)

# Measurement
z = array([[9]])     # Measurement [meter]

# Measurement covariance matrix
R = array([[2**2]])

# Design matrix
H = array([[1, 0]])

# Initial values
x = array([[0],
           [1]])
P = array([[0, 0],
           [0, 1]])

# Time update (prediction)
xp = phi@x
Pp = phi@P@phi.T + Q

print("\nPredicted state vector:\n", xp)
print("\nPredicted covariance matrix\n", Pp)

# Gain matrix
K = Pp@H.T@inv(H@Pp@H.T + R)

# Measurement update (correction)
x = xp + K@(z - H@xp)
P = (eye(2) - K@H)@Pp

print("\nEstimated state vector:\n", x)
print("\nEstimated covariance matrix\n", P)


Transition matrix:
 [[1.00 10.00]
 [0.00 1.00]]

Process noise matrix:
 [[83.33 12.50]
 [12.50 2.50]]

Predicted state vector:
 [[10.00]
 [1.00]]

Predicted covariance matrix
 [[183.33 22.50]
 [22.50 3.50]]

Estimated state vector:
 [[9.02]
 [0.88]]

Estimated covariance matrix
 [[3.91 0.48]
 [0.48 0.80]]
